//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templedunia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Table
    {
        public int Id { get; set; }
        public string blogTitle { get; set; }
        public string blogDate { get; set; }
        public string blogImage { get; set; }
        public string blogDetail { get; set; }
        public string blogStatus { get; set; }
        public string blogRTS { get; set; }
    }
}
