//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templedunia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class templeduniaEntities : DbContext
    {
        public templeduniaEntities()
            : base("name=templeduniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Login> Admin_Login { get; set; }
        public virtual DbSet<Blog_Table> Blog_Table { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactEnquire> ContactEnquires { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<TempleListing> TempleListings { get; set; }
    }
}
