//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templedunia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempleListing
    {
        public int Id { get; set; }
        public int sid { get; set; }
        public int did { get; set; }
        public int cid { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public string image4 { get; set; }
        public string seoTitle { get; set; }
        public string seoKeyword { get; set; }
        public string seoDesc { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> rts { get; set; }
    }
}
